[사다리게임] Step1,2  구현
SEUNGBOONG/java-ladder-func-playground pull request #1
Opened 2024-06-04 08:41 UTC by SEUNGBOONG

6/4 멘토님과 페어를 한덕에 어렵지만 나름 꾸역꾸역 구현한 것 같습니다.
특히 멘토님이 페어할사람이 없어서, 틀을 알려주시면서 해주셔서 감사했습니다. 
그래도 객체를 잘나눠가며 했던 것 같습니다. 수정할 때 편리했습니다.
근데 아직 메서드들을 완벽하게 이해하고 넘어가질 못해서 앞으로 조금 더 공부해서 사용해보도록 하겠고 로직을 
조금 더 연구해보도록 하겠습니다.  정적팩토리메서드를 사용하라 하셔서 정적팩토리메서드를 사용했고, 일급컬렉션으로 관리를 하려고 했습니다.

2024-06-05 07:50 UTC, sosow0212 requested changes
사다리 구현이 어려워서 힘드셨을텐데 수고 많으셨습니다.
누락된 테스트가 많고, 잘못된 테스트가 많이 있는데 이 부분 수정 부탁드립니다!

그리고 파일에서 마지막 개행이 자꾸 추가되지 않는데 확인 부탁드릴게요
몇 부분 수정하시고 조금만 다듬은 후에 다음 단계로 넘어가겠습니다!

2024-06-05 07:50 UTC, sosow0212 commented on README.md
> +## 생각 정리
ㅋㅋㅋ 이거 좋네요 어떤 고민을 했는지 알 수 있어서 리뷰할 때 도움 되는 것 같아요

2024-06-05 07:50 UTC, sosow0212 commented on src/main/java/Application.java
> +}
해당 클래스를 통해 컨트롤러에 view와 필요한 것들을 주입하고 실행시켜주세요!

2024-06-05 07:50 UTC, sosow0212 commented on src/main/java/controller/Controller.java
> +        Ladder ladder = generateLadders.generate(height, width);
GeneratorLadders가 필요한 이유가 있나요?
Ladder의 정적 팩토리 메서드를 통해 충분히 생성 가능할 것 같은데 어떻게 생각하시나요?!

2024-06-05 07:50 UTC, sosow0212 commented on src/main/java/model/GenerateLadder.java
> +}
```suggestion
public interface GenerateLadder {

    Ladder generate(int height, int width);
}
```

2024-06-05 07:50 UTC, sosow0212 commented on src/main/java/model/Height.java
> +        }
1. 메서드 분리로 어떤 역할을 하는지 명시해주면 좋을 것 같습니다.
2. CheckedException, UncheckedException에 대해 학습해보면 좋을 것 같습니다.
3. 이제는 IllegalArgumentException이 아닌 커스텀 예외를 만들어서 사용해보면 어떨까요?

2024-06-05 07:50 UTC, sosow0212 commented on src/main/java/model/Ladder.java
> +    private final Height height;
List와 같이 일급컬렉션 객체에서 다른 필드가 들어오면 안됩니다. (객체지향 생활체조 8번 규칙)
이렇게 사용하고 싶다면 `List<Lines> rowLines`를 감싼 객체를 만들고 Ladder에서 해당 객체와 Height를 같이 써야할 것 같아요!

2024-06-05 07:50 UTC, sosow0212 commented on src/main/java/model/Lines.java
> +    private static boolean isBeforePoint(boolean beforePoint, boolean nowPoint, final List<Line> lines) {
네이밍을 보고 어떤 메서드인지 감을 잡지 못할 것 같아요ㅠ

2024-06-05 07:50 UTC, sosow0212 commented on src/main/java/model/RowLines.java
> +    private static final int INITIAL_NUMBER = 0;
```suggestion
public class RowLines {

    private static final int INITIAL_NUMBER = 0;
```

2024-06-05 07:50 UTC, sosow0212 commented on src/main/java/view/InputView.java
> +}
EOF 문제가 아직도 발생하네요 [설정](https://hyeon9mak.github.io/github-no-newline-at-a-end-of-file/) 부탁드립니다!

2024-06-05 07:50 UTC, sosow0212 commented on src/main/java/view/OutputView.java
> +        StringBuilder response = new StringBuilder();
String, StringBuilder, StringBuffer의 차이점은 무엇일까요?

2024-06-05 07:50 UTC, sosow0212 commented on src/test/java/model/GenerateLaddersTest.java
> +
```suggestion
```

2024-06-05 07:50 UTC, sosow0212 commented on src/test/java/model/GenerateLaddersTest.java
> +    }
1. 테스트가 잘못된 것 같습니다. 검증부가 없습니다!

2. 
```suggestion
    void 사다리_생성_테스트() {
        // given
        GenerateLadders generateLadders = new GenerateLadders();
        
        // when
        generateLadders.generate(3,4);
        
        // then
    }
```

2024-06-05 07:50 UTC, sosow0212 commented on src/test/java/model/HeightTest.java
> +    }
이 부분도 테스트가 잘못 되었습니다.
`heightNumber = 3` 에서 3과 heightNumber가 같다고 하면 무조건 성공하는 테스트가 되는데 객체에서 값을 꺼내서 heightNumber와 비교해야할 것 같아요

2024-06-05 07:50 UTC, sosow0212 commented on src/test/java/model/HeightTest.java
> +        });
```suggestion
        // given
        int heightNumber = -1;

        // when & then
        Assertions.assertThrows(IllegalArgumentException.class, () -> {
            Height.from(heightNumber);
        });
```

2024-06-05 07:50 UTC, sosow0212 commented on src/test/java/model/LinesTest.java
> +        // then
1. 사용하지 않는 테스트는 제거해주세요
2. 해당 클래스의 로직도 테스트 해야할 것 같습니다. 정적 팩토리 메서드의 로직은 어떻게 테스트 해볼 수 있을까요?

2024-06-05 07:50 UTC, sosow0212 commented on src/test/java/model/RowLinesTest.java
> +        Assertions.assertEquals(rowLines1, rowLines);
1. 이 부분도 개행 변경해주세요. 추가적으로 Equals&Hashcode 에 대해서 학습해보시면 좋을 것 같습니다.
2. 테스트가 잘못된 것 같아요

2024-06-07 12:54 UTC, SEUNGBOONG commented on src/main/java/Application.java
> +}
넵 수정하겠습니다.

2024-06-07 12:55 UTC, SEUNGBOONG commented on src/test/java/model/RowLinesTest.java
> +        Assertions.assertEquals(rowLines1, rowLines);
[Equals&HashCode](https://mangkyu.tistory.com/101) 이거보고 공부해봤습니다.

2024-06-10 05:51 UTC, sosow0212 requested changes
리뷰 반영이 몇 가지가 안 되어있어서 확인 부탁드릴게요! 수고하셨습니다 👍

2024-06-10 05:51 UTC, sosow0212 commented on src/test/java/model/GenerateLaddersTest.java
> +        assertEquals(5, ladder.getHeight().getHeight());
assertAll이나 Softly를 사용해서 바꿔 보는 건 어떨까요?

2024-06-10 05:51 UTC, sosow0212 commented on src/test/java/model/GenerateLaddersTest.java
> +        assertEquals(3,ladder.getRowLines().size());
```suggestion
        // given
        Ladder ladder = Ladder.of(3,5);

        // when & then
        assertEquals(3, ladder.getRowLines().size());
```

2024-06-10 05:51 UTC, sosow0212 commented on src/test/java/model/HeightTest.java
> +}
EOF 문제 있습니다!

2024-06-10 05:51 UTC, sosow0212 commented on src/test/java/view/dto/LadderResponseTest.java
> +
```suggestion
```

2024-06-10 05:51 UTC, sosow0212 commented on src/test/java/model/GenerateLaddersTest.java
> +package model;
Model에 로직이 들어간 모든 부분은 테스트 해주세요!

2024-06-16 10:47 UTC, merged